import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// Retain verbatim notices for the production dependency closure of CLI/util.
/// Run at the workspace root after resolving the committed lockfile.
void main(List<String> args) {
  if (args.isNotEmpty && args.join(' ') != '--check') {
    throw ArgumentError('Usage: dart run tool/license_notices.dart [--check]');
  }
  final configFile = File('.dart_tool/package_config.json').absolute;
  final config = jsonDecode(configFile.readAsStringSync()) as Map;
  final roots = <String, Directory>{
    for (final package in config['packages'] as List)
      package['name'] as String: Directory.fromUri(
        configFile.uri.resolve(package['rootUri'] as String),
      ),
  };
  final visited = <String>{};
  final sections = <String, String>{};
  void visit(String name) {
    if (!visited.add(name)) return;
    final root = roots[name];
    if (root == null) {
      throw StateError('Unresolved production dependency: $name');
    }
    final spec = loadYaml(
      File(p.join(root.path, 'pubspec.yaml')).readAsStringSync(),
    ) as YamlMap;
    final dependencies = spec['dependencies'] as YamlMap?;
    for (final dependency in dependencies?.keys ?? []) {
      visit(dependency as String);
    }
    if (name == 'marionette_agent' ||
        name == 'marionette_agent_util' ||
        name == 'example') {
      return;
    }
    final notices =
        root.listSync().whereType<File>().where((file) {
            final basename = p.basename(file.path).toUpperCase();
            return basename.startsWith('LICENSE') ||
                basename == 'COPYING' ||
                basename == 'NOTICE' ||
                basename.startsWith('NOTICE.');
          }).toList()
          ..sort((a, b) => p.basename(a.path).compareTo(p.basename(b.path)));
    if (!notices.any(
      (f) =>
          p.basename(f.path).toUpperCase().startsWith('LICENSE') ||
          p.basename(f.path).toUpperCase() == 'COPYING',
    )) {
      throw StateError(
        'No license found for $name; review before distribution',
      );
    }
    sections[name] = [
      '$name ${spec['version'] ?? '(SDK)'}',
      'Source: ${spec['repository'] ?? spec['homepage'] ?? 'Flutter SDK'}',
      for (final file in notices)
        '\n--- ${p.basename(file.path)} ---\n${file.readAsStringSync().replaceAll('\r\n', '\n').trimRight()}',
    ].join('\n');
  }

  visit('marionette_agent');
  visit('example');
  // A compiled Dart executable also contains the Dart runtime.
  final sdkLicense = File(
    p.join(p.dirname(Platform.resolvedExecutable), '..', 'LICENSE'),
  );
  sections['Dart SDK'] =
      'Dart SDK (runtime)\nSource: https://github.com/dart-lang/sdk\n\n${sdkLicense.readAsStringSync().trimRight()}';
  final names = sections.keys.toList()..sort();
  final output =
      'Third-party notices for marionette_agent\n'
      'Generated by tool/license_notices.dart from resolved production dependencies.\n'
      'Includes the CLI/util/example dependency closure and Dart runtime; some components\n'
      'are only used by the app-side util. Original notices remain verbatim.\n\n'
      '${names.map((name) => '${'=' * 72}\n${sections[name]}').join('\n\n')}\n';
  final destination = File('THIRD_PARTY_NOTICES.txt');
  if (args.contains('--check')) {
    if (!destination.existsSync() || destination.readAsStringSync() != output) {
      stderr.writeln(
        'Third-party notices are stale. Run dart run tool/license_notices.dart and review the result.',
      );
      exitCode = 1;
      return;
    }
  } else {
    destination.writeAsStringSync(output);
  }
  stdout.writeln('Verified notices for ${sections.length} components.');
}
