name: marionette_agent_util
description: Internal platform services for marionette_agent.
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.13.2
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
