name: Sync labels

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml

permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Sync repository labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: true
          token: ${{ secrets.GITHUB_TOKEN }}
